// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OPC.UAFx.Client.Service.Models;

#nullable disable

namespace OPC.UAFx.Client.Service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241101105334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("OPC.UAFx.Client.Service.Models.MaquinaOee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("CiclosTotal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoMaquina")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MinutosTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("ProducaoTotal")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RejeitosTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MaquinaOees");
                });
#pragma warning restore 612, 618
        }
    }
}
